# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: flavourtown Gradle CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build

    ##aws s3 create bucket
    - name: flavourtown
      # You may pin to the exact commit or the version.
#      uses: aitorres/aws-s3-create-bucket@bf2701c2732789d5924ae02b68976343a31f6db5
#      uses: aitorres/aws-s3-create-bucket@v1.2.0
      with:
        # Name of the bucket that will be created (make sure it is unique)
        bucket-name: flavourtown
        # AWS Access Key ID
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        # AWS Secret Access Key
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        # AWS Region (default: us-east-1)
        aws-region: ap-northeast-2
        # default is us-east-1
        # ACL to apply to the bucket during creation (default: private)
        acl: private
        # default is private

#    # 전송할 파이릉ㄹ 담을 디렉토리 생성
#    - name: Make Directory for deliver
#      run: mkdir deploy
#
#    # Jar 파일 Copy
#    - name: Copy Jar
#      run: cp ./build/libs/*.jar ./deploy/
#
#    # 압축파일 형태로 전달
#    - name: Make zip file
#      run: zip -r ./springboot-with-githubaction.zip ./deploy
#
#    # S3 Bucket으로 copy
#    - name: Deliver to AWS S3

#      env:
#        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#      run: |
#        aws s3 cp \
#        --region ap-northeast-2 \
#        --acl private \
#        ./springboot-intro-build.zip s3://springboot-intro-build/
#
#
##==============##
